name: UI Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
    # Configurar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Instalar dependencias
    - name: Install dependencies
      run: npm install

    # Iniciar pruebas
    - name: Run UI Tests
      run: npx wdio run wdio.conf.js
